import defineActionTypes from '../utils/defineActionTypes'

export default defineActionTypes({
  /*
   * View model
   */
  AUTH: `
    CONFIGURE_START
    CONFIGURE_COMPLETE
    CONFIGURE_ERROR
    AUTHENTICATE_START
    AUTHENTICATE_COMPLETE
    AUTHENTICATE_ERROR
    SIGN_IN_START
    SIGN_IN_COMPLETE
    SIGN_IN_ERROR
    SIGN_IN_FORM_UPDATE
    SIGN_UP_START
    SIGN_UP_COMPLETE
    SIGN_UP_ERROR
    SIGN_UP_FORM_UPDATE
    SIGN_OUT_START
    SIGN_OUT_COMPLETE
  `,

  ENTITIES: `
    REQUESTED
    RECEIVED
    RECEIVED_LIST
  `,

  ACCOUNTS: `
    LIST_START
    LIST_COMPLETE
    LIST_ERROR
    LIST_REF_START
    LIST_REF_COMPLETE
    LIST_REF_ERROR
    CREATE_START
    CREATE_COMPLETE
    CREATE_ERROR
    CREATE_FORM_UPDATE
    CREATE_REF_START
    CREATE_REF_COMPLETE
    CREATE_REF_ERROR
    CREATE_REF_FORM_UPDATE
    CREATE_REF_OWNER_LOOKUP_START
    CREATE_REF_OWNER_LOOKUP_COMPLETE
    CREATE_REF_ACCOUNT_LOOKUP_START
    CREATE_REF_ACCOUNT_LOOKUP_COMPLETE
  `,

  ACCOUNT: `
    SINGLE_START
    SINGLE_COMPLETE
    SINGLE_ERROR
    DELETE_START
    DELETE_COMPLETE
    DELETE_ERROR
  `,

  ERROR: `
    START
    STOP
  `

})
